#!/bin/sh
set -e

if [ -d /run/systemd/system ]; then
  systemctl daemon-reload >/dev/null 2>&1 || true
  systemctl reset-failed watchmouse-host >/dev/null 2>&1 || true
fi

gtk-update-icon-cache -f /usr/share/icons/hicolor 2>/dev/null || true

exit 0