#!/bin/sh
set -e

if [ -d /run/systemd/system ] && [ "$1" = "remove" ]; then
  systemctl stop watchmouse-host >/dev/null 2>&1 || true
  systemctl disable watchmouse-host >/dev/null 2>&1 || true
fi

exit 0